name: Linux Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  PYTHON_VERSION: 3.12.2
  FLUTTER_VERSION: 3.24.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Python Dependencies
        working-directory: ./GUI
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Setup Flutter ${{ env.FLUTTER_VERSION }}
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Patch for linux build
        run: |
          flutter doctor
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
          flutter doctor
      - name: Flet Build Linux
        working-directory: ./GUI
        run: |
          flutter config --no-analytics
          flet pack main.py --verbose

      - name: Copy assets
        working-directory: ./GUI
        run: cp -r ./assets ./dist/assets

      - name: Zip dist flder
        working-directory: ./GUI
        run: zip -r srtranslator.zip ./dist

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4.3.4
        with:
          name: linux-build-artifact
          path: ./GUI/srtranslator.zip
          if-no-files-found: error
          overwrite: false
