name: Windows Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  PYTHON_VERSION: 3.12.2
  FLUTTER_VERSION: 3.24.0

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Python Dependencies
        working-directory: ./GUI
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Setup Flutter ${{ env.FLUTTER_VERSION }}
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Flet Build Windows
        working-directory: ./GUI
        run: |
          flutter config --no-analytics
          flet pack main.py --verbose

      - name: Copy assets
        working-directory: ./GUI
        run: cp -r ./assets ./dist/assets

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4.3.4
        with:
          name: windows-build-artifact
          path: ./GUI/dist
          if-no-files-found: error
          overwrite: false
